name: Deta Deploy
description: Simple GitHub Action to deploy current repo to a Deta Micro

inputs:
  deta-access-token:
    description: "Deta access token."
    required: true
  deta-name:
    description: "Deta Micro name."
    required: true
  deta-project:
    description: "Deta project name."
    default: "default"
  deta-project-dir:
    description: "Directory of the project to be deployed."
    default: "."

runs:
  using: "composite"
  steps:
    # Install Deta CLI as per docs
    # https://docs.deta.sh/docs/cli/install
    - name: Install Deta CLI
      shell: bash
      run: |
        curl -fsSL https://get.deta.dev/cli.sh | sh

    # Using the access token and existing Deta Micro and project,
    # clone the Micro and copy `.deta` metadata folder to use it in deploy
    # https://docs.deta.sh/docs/cli/commands#deta-clone
    - name: Clone Deta Metadata
      shell: bash
      run: |
        export DETA_ACCESS_TOKEN=${{ inputs.deta-access-token }}
        mkdir -p tmp/${{ inputs.deta-name }}
        ~/.deta/bin/deta clone --name ${{ inputs.deta-name }} --project ${{ inputs.deta-project }} tmp/${{ inputs.deta-name }}
        cp -r tmp/${{ inputs.deta-name }}/.deta ${{ inputs.deta-project-dir }}
        rm -rf tmp/${{ inputs.deta-name }}
        # Delete the `tmp` directory if it is empty
        if ! [ "$(ls -A tmp/)" ]; then
            rm -r tmp/
        fi

    # Using the access token, deploy the project to Deta
    # https://docs.deta.sh/docs/cli/commands#deta-deploy
    - name: Deploy to Deta
      shell: bash
      run: |
        export DETA_ACCESS_TOKEN=${{ inputs.deta-access-token }}
        cd ${{ inputs.deta-project-dir }}
        ~/.deta/bin/deta deploy

branding:
  icon: check-circle
  color: purple
